### ISSUE TITLE
[Devices] Add Thermal Sensation to termomether devices

### ISSUE THREAD

**Issue by danimart1991** [danimart1991/esphome-config#5]
Analyse and include Thermal Sensation/Thermal Confort/Heat Index... to all the devices that brings temperature + humidity. 

This improves all the automations because 22ºC in Winter is completely different to 22ºC in Summer.

**Comment by danimart1991** [comment]
@LeidenSpain uses a formula like:

```yaml
sensor:
  - platform: template
    sensors:
      windchill_balcon:
        value_template: "{{ (states('sensor.balcon_temperatura')|float + 0.348*(((states('sensor.balcon_humedad')|float/100)*6.105)*(2.71828**((17.27*states('sensor.balcon_temperatura')|float)/(237.7+states('sensor.balcon_temperatura')|float)))) - 4.25) | round(2) }}"
        friendly_name: Sensación térmica
        icon_template: mdi:thermometer-lines
        device_class: temperature   
        unit_of_measurement: '°C'
```

Muxa in discord (ESPHome-General) recommends:
- https://en.m.wikipedia.org/wiki/Thermal_comfort
- https://en.m.wikipedia.org/wiki/Heat_index (he think this is only for high temperatures)
