### ISSUE TITLE
[Devices] Improve Plugs devices with ESPHome-Configs templates

### ISSUE THREAD

**Issue by danimart1991** [danimart1991/esphome-config#6]
In https://esphome-configs.io there are plugs with templates that has some improvements over my current plug templates. Update all my devices with this improvements.

Example: https://esphome-configs.io/devices/blitzwolf-bw-shp2-power-monitoring-plug/

```yaml
# Blink the blue light if we aren't connected to WiFi. Could use https://esphome.io/components/status_led.html instead but then we couldn't use the blue light for other things as well.
# Only if not connected after 30s
interval:
  - interval: 2000ms
    then:
      - if:
          condition:
            for:
              time: 30s
              condition:
                not:
                  wifi.connected:
          then:
            - light.turn_on:
                id: ${devicename}_blue_led
                brightness: 100%
```
